---
title: ショート動画作成ツール
---
erDiagram
    skills["Agent Skill"] {
        uuid skill_id PK "Agent SkillID"
        text skill  "スキル"
        timestamptz created_at "作成日"
        timestamptz updated_at "更新日"
    }