---
title: 認証・認可
---
sequenceDiagram
    autonumber
    box Web
    participant OpenWebUI_Frontend
    end

    box Interface
    end
    
    box Application
    participant OpenWebUI_Backendend
    end

    box Middleware
    end
    
    box Repository
    participant Redis
    participant PostgreSQL
    participant PGVector
    participant MinIO
    end

    box Google
    participant OAuthClient
    participant FoundationModel
    end

    box OpenWebUI
    participant Models
    participant Knowledge
    participant Prompts
    participant Skills
    participant MCP
    participant WorkspaceTools
    participant PipesFunctions
    participant FiltersFunctions
    participant ActionsFunctions
    end

    box Descript
    participant DescriptMCP
    participant DescriptApp
    end

    box OpenAI
    participant LLMModel
    participant EmbeddingModel
    participant DiffusionModel
    participant STTModel
    participant TTSModel
    participant RealtimeModel
    end

    Note over OpenWebUI_Frontend,OAuthClient: 認証
    OpenWebUI_Frontend->>OAuthClient: 認証・認可(OIDC)

    alt 成功
        OAuthClient-->>OpenWebUI_Frontend: Claim情報
        
    else 失敗
        OAuthClient-->>OpenWebUI_Frontend: 結果

    end

    
