---
title: 認証・認可
---
sequenceDiagram
    autonumber
    box Web
    participant OpenWebUI-Frontend
    end

    box Interface
    end
    
    box Application
    participant OpenWebUI-Backendend
    end

    box Middleware
    end
    
    box Repository
    participant Redis
    participant PostgreSQL
    participant PGVector
    participant MinIO
    end

    box OpenWebUI
    participant Models
    participant Knowledge
    participant Prompts
    participant Skills
    participant MCP
    participant WorkspaceTools
    participant PipesFunctions
    participant FiltersFunctions
    participant ActionsFunctions
    end

    box OpenAI
    participant LLMModel
    participant EmbeddingModel
    end

    box OpenAI
    participant LLMModel
    participant EmbeddingModel
    end

    Note over NextJS,Cognito: 認証
    NextJS->>Cognito: 認証情報
    Cognito->>Cognito: 認証・認可(OIDC)
    Cognito-->>NextJS: Claim情報