---
title: 動画
---
sequenceDiagram
    autonumber
    box Web
    participant OpenWebUI_Frontend
    end

    box Interface
    end
    
    box Application
    participant OpenWebUI_Backendend
    end

    box Middleware
    end
    
    box Repository
    participant Redis
    participant PostgreSQL
    participant PGVector
    participant MinIO
    end

    box Google
    participant OAuthClient
    end

    box OpenWebUI
    participant Models
    participant Knowledge
    participant Prompts
    participant Skills
    participant MCP
    participant WorkspaceTools
    participant ActionsFunctions
    participant PipesFunctions
    participant FiltersFunctions
    end

    box Descript
    participant DescriptMCP
    participant DescriptApp
    end

    box OpenAI
    participant LLMModel
    participant EmbeddingModel
    participant DiffusionModel
    participant STTModel
    participant TTSModel
    participant RealtimeModel
    end

    Note over OpenWebUI_Frontend,DescriptApp: 動画のアップロード
    OpenWebUI_Frontend->>ActionsFunctions: 動画のアップロード

    ActionsFunctions->>OpenWebUI_Frontend: 入力フォーム(プロジェクト名, 動画)
    OpenWebUI_Frontend-->>ActionsFunctions: 結果

    ActionsFunctions->>PipesFunctions: 動画のアップロード

    PipesFunctions->>DescriptMCP: プロジェクト一覧

    DescriptMCP->>DescriptApp: List projects(name)
    DescriptMCP->>DescriptApp: Import media and sequences(project_name)

    DescriptMCP-->>PipesFunctions: 結果
    PipesFunctions-->>ActionsFunctions: 結果
    ActionsFunctions-->>OpenWebUI_Frontend: 結果

    Note over OpenWebUI_Frontend,DescriptApp: 動画の編集
    OpenWebUI_Frontend->>ActionsFunctions: 動画の編集

    ActionsFunctions->>PipesFunctions: プロジェクトの取得

    PipesFunctions->>DescriptMCP: プロジェクト一覧を取得

    DescriptMCP->>DescriptApp: List projects

    alt 0件以上
        DescriptMCP-->>PipesFunctions: 結果
        PipesFunctions-->>ActionsFunctions: 結果

        ActionsFunctions->>OpenWebUI_Frontend: 入力フォーム(プロジェクト名選択)
        OpenWebUI_Frontend-->>ActionsFunctions: 結果

        ActionsFunctions->>PipesFunctions: プロジェクトの取得
        
        PipesFunctions->>DescriptMCP: プロジェクトの取得
        DescriptMCP->>DescriptApp: Get project details(name)
        DescriptMCP-->>PipesFunctions: 結果
        PipesFunctions-->>ActionsFunctions: 結果

        ActionsFunctions->>OpenWebUI_Frontend: 入力フォーム(プロジェクトに含まれている動画の表示, 編集指示)
        OpenWebUI_Frontend-->>ActionsFunctions: 結果

        ActionsFunctions->>PipesFunctions: 動画の編集

        PipesFunctions->>Prompts: システムプロンプトの取得
        PipesFunctions->>Models: モデルの取得

        Models->>LLMModel: モデルの取得
        Models-->>PipesFunctions: 結果

        PipesFunctions->>LLMModel: システムプロンプト,編集指示から編集プロンプトを生成
        
        loop 確定するまで
            PipesFunctions->>DescriptMCP: 動画編集
            DescriptMCP->>DescriptApp: Agent edit(project_name,prompt)
            DescriptMCP-->>PipesFunctions: 結果

            PipesFunctions->>DescriptMCP: 動画をダウンロード
            DescriptMCP->>DescriptApp: Publish project media(project_id,media_type)
            DescriptMCP-->>PipesFunctions: 結果
            PipesFunctions-->>ActionsFunctions: 結果

            ActionsFunctions->>OpenWebUI_Frontend: 入力フォーム(exported動画の表示, 編集指示, 確定)
            OpenWebUI_Frontend-->>ActionsFunctions: 結果
            ActionsFunctions->>PipesFunctions: 結果

        end

        PipesFunctions->>DescriptMCP: 動画をダウンロード
        DescriptMCP->>DescriptApp: Publish project media(project_id,media_type)
        DescriptMCP-->>PipesFunctions: 結果
        PipesFunctions-->>ActionsFunctions: 結果
        ActionsFunctions-->>OpenWebUI_Frontend: 結果

        
    else それ以外
        DescriptMCP-->>PipesFunctions: 結果
        PipesFunctions-->>ActionsFunctions: 結果
        ActionsFunctions-->>OpenWebUI_Frontend: 結果

    end

    Note over OpenWebUI_Frontend,DescriptApp: タイムラインのエクスポート
    OpenWebUI_Frontend->>ActionsFunctions: タイムラインのエクスポート

    ActionsFunctions->>PipesFunctions: プロジェクトの取得

    PipesFunctions->>DescriptMCP: プロジェクト一覧を取得

    DescriptMCP->>DescriptApp: List projects

    alt 0件以上
        DescriptMCP-->>PipesFunctions: 結果
        PipesFunctions-->>ActionsFunctions: 結果

        ActionsFunctions->>OpenWebUI_Frontend: 入力フォーム(プロジェクト名選択)
        OpenWebUI_Frontend-->>ActionsFunctions: 結果

        ActionsFunctions->>PipesFunctions: プロジェクトの公開

        PipesFunctions->>DescriptMCP: プロジェクトの公開
        DescriptMCP->>DescriptApp: Publish project media(project_id,media_type)
        DescriptMCP-->>PipesFunctions: 結果
        PipesFunctions-->>ActionsFunctions: 結果
        ActionsFunctions-->>OpenWebUI_Frontend: 結果

        OpenWebUI_Frontend->>DescriptApp: プロジェクトに遷移
        
        DescriptApp->>DescriptApp: Timeline export
        
    else それ以外
        DescriptMCP-->>PipesFunctions: 結果
        PipesFunctions-->>ActionsFunctions: 結果
        ActionsFunctions-->>OpenWebUI_Frontend: 結果

    end

    
